import 'package:intl/intl.dart';

class AppUtils {
  /// Formated Date time function
  /// Returns current date & time formatted as "d MMMM yyyy : h:mm a"
  static String getFormattedDateTime() {
    return DateFormat("d MMMM yyyy : h:mm a").format(DateTime.now());
  }

  /// Passage list
  final passages = {
    "Easy": [
      "Flutter is an open-source framework by Google that helps developers create cross-platform apps for mobile, web, and desktop using a single codebase, making development fast and efficient.",
      "Dart is the programming language used in Flutter, known for its simplicity, strong typing, and fast execution speed, which makes building applications smooth, reliable, and beginner-friendly.",
      "State management in Flutter is important because it helps developers control how data changes affect the user interface, making apps dynamic, consistent, and easy to maintain.",
      "Using Flutter, developers can quickly build user interfaces with widgets that are customizable and flexible, helping them create visually appealing and responsive applications in less time.",
      "Flutter applications are compiled to native machine code, which means they deliver high performance across both iOS and Android platforms without sacrificing speed, responsiveness, or overall user experience.",
      "Hot reload is a special Flutter feature that allows developers to instantly see the results of code changes in real time, saving time during testing and debugging.",
      "Widgets are the building blocks of Flutter applications, and everything from buttons, text, layouts, and even entire screens are made up of widgets in Flutter development.",
      "Flutter’s growing community makes it easier for new developers to find tutorials, packages, and guidance online, ensuring learning and development remain simple, quick, and well-supported.",
      "Cross-platform development using Flutter reduces time and cost for companies, since developers don’t need to build separate applications for Android and iOS individually, making the process efficient.",
      "Flutter is widely used in both startups and large companies, as it provides beautiful design, quick development, and high performance, making it a popular choice worldwide."
    ],
    "Medium": [
      "Flutter is a modern cross-platform framework created by Google that allows developers to build mobile, web, and desktop applications with a single codebase. It uses the Dart programming language, which is easy to learn and offers excellent performance. Developers enjoy Flutter because of its customizable widgets, fast development cycles, and hot reload feature, which makes it simple to test changes instantly without restarting the app.",
      "State management in Flutter is one of the most important concepts for developers to learn. It helps to decide how data flows and updates inside an app, making the application dynamic and consistent. Tools like Provider, Riverpod, or GetX offer developers different approaches to manage state effectively. Choosing the right state management strategy is crucial, as it impacts the app’s performance, maintainability, and overall development experience.",
      "GetX is a popular package for Flutter that offers a simple yet powerful way to manage application state, navigation, and dependencies. It reduces boilerplate code, making development faster and more efficient. Developers like GetX because it combines multiple features into one package, eliminating the need to install many separate libraries. It is especially useful for medium-sized apps where simplicity and performance are both priorities.",
      "Flutter applications can be designed with widgets that are both flexible and reusable, allowing developers to create beautiful user interfaces quickly. Since everything in Flutter is a widget, developers gain more control over customization. However, understanding how the widget tree works is important, as deeply nested widgets can sometimes affect performance. This makes learning layout optimization an essential part of the development journey.",
      "Asynchronous programming is an important concept in Dart and Flutter. Developers often work with APIs, databases, or files that take time to respond. Dart offers Futures, async-await, and Streams to handle such tasks without blocking the main thread. Mastering these tools helps developers build responsive applications that continue working smoothly even when tasks like network requests take longer than expected.",
      "Flutter’s widget-based architecture allows developers to build apps by combining smaller parts into a larger structure. This modular approach makes apps easier to maintain and expand in the future. Developers can reuse components like buttons or cards across multiple screens, ensuring consistency throughout the application. Understanding this concept is vital for building scalable applications that grow without creating technical debt.",
      "One of Flutter’s strengths lies in its ability to provide a consistent user experience across multiple platforms. Whether the app runs on Android, iOS, web, or desktop, the look and behavior remain the same. This saves time and effort for developers, as they do not need to design and test separate versions for each platform, which often reduces overall development cost.",
      "Learning Flutter is easier when developers practice regularly by building small projects. Starting with simple apps like a calculator, to-do list, or quiz application helps them understand how widgets work together. Once the basics are clear, they can move on to more complex projects such as chat applications or e-commerce apps, which require knowledge of networking, state management, and database handling.",
      "Performance optimization in Flutter involves writing efficient code and avoiding unnecessary widget rebuilds. Developers can use tools like the Flutter DevTools profiler to analyze how their apps behave. They can also split the widget tree into smaller components to reduce complexity. Optimizing performance ensures that applications run smoothly on all devices, including low-end smartphones, where resources may be limited.",
      "The Flutter ecosystem is growing quickly, with thousands of packages available to simplify development. These packages allow developers to add features such as authentication, maps, payments, and animations without writing everything from scratch. Choosing reliable and well-maintained packages is important for long-term stability. This community support is one reason why Flutter continues to grow in popularity worldwide."
    ],
    "Hard": [
      "Asynchronous programming in Flutter and Dart is a key concept that every developer must understand when building scalable applications. Many tasks such as network requests, database operations, or file system access take time to complete, and handling them synchronously would block the main thread, causing the application to freeze. Dart provides several tools such as Futures, async-await, and Streams to manage asynchronous tasks. Futures represent a single value that will be available in the future, while Streams handle multiple values delivered over time. Developers must also learn to handle exceptions gracefully to avoid crashes, ensuring that the application remains responsive and user-friendly even under heavy workloads or poor network conditions.",
      "The widget tree is the foundation of every Flutter application, and while it provides flexibility for creating complex user interfaces, it also introduces challenges for beginners. Flutter builds its user interface by combining widgets into a tree-like structure where each widget is responsible for a specific part of the screen. Deeply nested widget trees can impact performance if not managed carefully. Developers can optimize this by breaking large trees into smaller reusable components and by using efficient state management solutions such as GetX, Riverpod, or Provider. Mastering the widget tree is an important skill for developers who aim to create scalable, maintainable, and high-performing applications.",
      "Typing accuracy is more important than typing speed in real-world scenarios, as accurate typing reduces the risk of errors and miscommunication. In professional environments, error-free communication is critical, whether writing emails, documentation, or code. While speed can help increase productivity, errors often result in wasted time for corrections. Improving accuracy involves practicing proper finger placement, reducing reliance on autocorrect, and gradually increasing speed only when accuracy is consistent. Developers, writers, and students all benefit from prioritizing accuracy, as it ensures clarity, professionalism, and confidence in their communication, whether through writing software, academic papers, or workplace documents.",
      "State management is a critical aspect of Flutter application development that directly influences how data flows through the app and how the user interface responds to changes. Poor state management often leads to unnecessary widget rebuilds, inconsistent behavior, or complex code that becomes hard to maintain. Flutter developers have access to multiple approaches for handling state, ranging from simple setState for small apps to advanced solutions like Bloc, GetX, or Riverpod for larger projects. Choosing the right solution depends on the complexity of the project, the number of developers involved, and the need for scalability. A good understanding of state management enables developers to deliver efficient, stable, and maintainable apps.",
      "Building cross-platform applications is one of the main reasons developers choose Flutter. With a single codebase, they can deploy apps on Android, iOS, web, and even desktop, saving both time and money. However, maintaining performance across all platforms requires attention to detail, as device-specific behaviors can sometimes affect the experience. For example, scroll physics differ between iOS and Android, and developers must customize behavior to meet platform expectations. Additionally, responsive design plays an important role in ensuring apps look good on devices with different screen sizes. Flutter provides tools such as MediaQuery and LayoutBuilder that help developers create adaptive and consistent designs.",
      "Learning asynchronous programming is often difficult for beginners, as they may not fully understand how tasks run in the background while the main thread continues executing. In Dart, the event loop plays a key role in managing asynchronous operations. Futures schedule tasks to complete later, while Streams handle sequences of asynchronous data. Mastering these concepts requires practice with APIs, file reading, and user input handling. Without a good understanding of async, developers risk creating unresponsive apps. Proper use of await, try-catch blocks, and stream listeners ensures apps remain stable and user-friendly, even when dealing with unpredictable data or slow networks.",
      "Flutter’s hot reload feature is a powerful tool that allows developers to instantly apply code changes without restarting the entire application. This dramatically reduces development time and improves productivity. However, it is important to understand its limitations. Hot reload can update most changes in the widget tree, but some updates, such as those in global variables or initialization logic, may require a full restart. Developers must also be cautious when making structural changes to widgets, as hot reload may not always behave as expected. By combining hot reload with proper debugging practices, developers can create a smooth and efficient development workflow.",
      "Performance optimization in Flutter involves several techniques that ensure the app runs efficiently even on low-end devices. Avoiding unnecessary rebuilds is one of the most important strategies, which can be achieved by using const constructors, splitting widgets into smaller components, and using state management properly. Developers should also minimize expensive operations inside build methods and instead perform heavy work asynchronously. Tools like Flutter DevTools help identify performance bottlenecks, memory leaks, or excessive widget rebuilds. Optimizing images, reducing package dependencies, and caching frequently used data also contribute to better performance, ensuring users enjoy a smooth and reliable experience.",
      "Testing is an integral part of building robust Flutter applications. Developers should write unit tests for small pieces of logic, widget tests for UI components, and integration tests for full workflows. Flutter provides a testing framework out of the box, which makes it easy to verify app functionality before deployment. Automated testing reduces the risk of introducing bugs when making changes, especially in large projects with multiple contributors. Continuous integration tools can further streamline testing by automatically running test suites whenever code is pushed to a repository. A strong testing culture improves app stability, developer confidence, and overall user satisfaction.",
      "The Flutter ecosystem continues to grow rapidly, with frequent updates and an expanding community. Google regularly releases improvements to Flutter and Dart, focusing on performance, new widgets, and better tooling support. The community contributes by creating open-source packages, tutorials, and plugins that make development faster and easier. For developers, keeping up with these changes is important to stay productive and competitive. Participating in community forums, attending meetups, and contributing to open source projects not only helps developers learn but also ensures they remain up to date with the latest best practices and innovations in Flutter development."
    ]
  };
}
